name: heroku
on:
  workflow_dispatch:
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest
  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: heroku checkout
        uses: akhileshns/heroku-deploy@v3.12.12
