# Generated CI/CD Pipeline YAML
# This YAML is compatible with GitHub Actions

# Pipeline: tutorial_pipeline
name: tutorial_pipeline

on:
  workflow_dispatch:

jobs:
  build_test:
    # Build and test the application
    runs-on: ubuntu-latest
    steps:
            - name: command_18305
              uses: actions/checkout@v4
            - name: setup node.js
              uses: actions/node@v3
              with:
                        node-version: '18'
                        distribution: 'temurin'
            - name: dependencies
              run: yarn install
            - name: tests
              run: yarn test
  heroku:
    # deploy heroku
    runs-on: ubuntu-latest
    steps:
            - name: command_38517
              uses: actions/checkout@v4
            - name: setup heroku
              uses: akhileshns/heroku-deploy@v3.12.12
